import type { Meta, StoryObj } from "@storybook/react";

import Game from "../components/Game";

const meta = {
  title: "Components/Game",
  component: Game,
  parameters: {
    layout: "centered",
  },
} satisfies Meta<typeof Game>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Empty: Story = {
  args: {},
};

export const XWins: Story = {
  args: {
    initialGameState: {
      turn: "X",
      board: [
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          "X",
          undefined,
          undefined,
          "X",
          undefined,
          "O",
          "X",
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          "X",
          "X",
          "X",
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          "O",
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          "X",
          "X",
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          undefined,
        ],
      ],
    },
  },
};

export const XAboutToWin: Story = {
  args: {
    initialGameState: {
      turn: "X",
      board: [
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          "X",
          undefined,
          undefined,
          "X",
          undefined,
          "O",
          "X",
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          "X",
          "X",
          "X",
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          "O",
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          "X",
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          undefined,
        ],
      ],
    },
  },
};

export const OWins: Story = {
  args: {
    initialGameState: {
      turn: "X",
      board: [
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          "O",
          undefined,
          undefined,
          "O",
          undefined,
          "X",
          "O",
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          undefined,
        ],
        [
          undefined,
          "X",
          undefined,
          undefined,
          "X",
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          "O",
          "O",
          "O",
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          undefined,
          undefined,
          undefined,
          undefined,
        ],
        [
          undefined,
          "X",
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          "X",
          undefined,
        ],
        [
          undefined,
          "X",
          undefined,
          undefined,
          undefined,
          undefined,
          "O",
          "O",
          "O",
        ],
        [
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          "X",
          undefined,
        ],
      ],
    },
  },
};
